### ISSUE TITLE
请问如何通过Nginx进行部署

### ISSUE THREAD

**Issue by siyuanxu** [deluxghost/DelogX#4]
Delogx很简洁，理念很好。但是没有找到相关文档，作为刚刚接触flask的新人，暂时不了解如何正式进行部署。现在博客只能通过domain_name:8000访问，请问如何通过Nginx部署并指定sever_name。

**Comment by deluxghost** [comment]
你好，DelogX暂时还没写文档，因为的确还没有完整测试各种部署方式，这两个月也没有在这上面花时间。实际上**暂时还不知道如何在nginx上部署成功**，但是Apache、Tornado等其他支持的方式已经测试过了。
现在的版本刚刚有独立部署方式的雏形，是在创建博客实例时加上一个部署参数来生成相应的wsgi文件，对于nginx/uwsgi来说，就是在init时执行`delogx init --uwsgi`，这样生成的文件就包括一个uwsgi.py，作为uwsgi的配置文件。
Flask的官方文档里面关于Nginx/uwsgi的部署说明在[这里](http://flask.pocoo.org/docs/0.12/deploying/uwsgi/)，但是不适用DelogX，因为DelogX并不是按照标准的Flask应用来做的，并且，用的是配置文件而不是官方文档里面的参数方式。
此外，DelogX的演示页面是旧版，没有更新，请不要阅读那上面的说明。如果我哪天测试Nginx的部署成功了，会在这里回复。

**Comment by siyuanxu** [comment]
感谢你的回复。
在deploy文件夹中找到了uwsgi.py文件，复制到根目录后使用gunicorn运行成功。
`gunicorn -w 4 -b 127.0.0.1:8000 uwsgi:application`
暂时使用Nginx的反向代理，可以达到直接访问域名的目的。

**Comment by deluxghost** [comment]
嗯，反代确实可以，不过uwsgi的socket方法我还是得测试过了才好落笔。

**Comment by deluxghost** [comment]
implemented
